# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server_messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15server_messages.proto\"D\n\tDBAccount\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x11\n\tlogged_in\x18\x02 \x01(\x05\x12\x12\n\ncreated_at\x18\x03 \x01(\t\"\x83\x01\n\tDBMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\x0fsender_username\x18\x02 \x01(\t\x12\x19\n\x11reciever_username\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x11\n\tdelivered\x18\x05 \x01(\x05\x12\x12\n\ncreated_at\x18\x06 \x01(\t\"O\n\rSyncDBRequest\x12\x16\n\x0eserver_address\x18\x01 \x01(\t\x12\x13\n\x0bserver_port\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"e\n\x0eSyncDBResponse\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x1f\n\x0b\x64\x62_accounts\x18\x02 \x03(\x0b\x32\n.DBAccount\x12\x1f\n\x0b\x64\x62_messages\x18\x03 \x03(\x0b\x32\n.DBMessage2=\n\x0eServerExchange\x12+\n\x06SyncDB\x12\x0e.SyncDBRequest\x1a\x0f.SyncDBResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DBACCOUNT._serialized_start=25
  _DBACCOUNT._serialized_end=93
  _DBMESSAGE._serialized_start=96
  _DBMESSAGE._serialized_end=227
  _SYNCDBREQUEST._serialized_start=229
  _SYNCDBREQUEST._serialized_end=308
  _SYNCDBRESPONSE._serialized_start=310
  _SYNCDBRESPONSE._serialized_end=411
  _SERVEREXCHANGE._serialized_start=413
  _SERVEREXCHANGE._serialized_end=474
# @@protoc_insertion_point(module_scope)
